// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN6bRrn3euDeoPzFzhfPUAu4CwvMLzLmg',
    appId: '1:239664079474:web:a5798e0854f95d9e11d8eb',
    messagingSenderId: '239664079474',
    projectId: 'fir-esp32-demo-6968d',
    authDomain: 'fir-esp32-demo-6968d.firebaseapp.com',
    databaseURL: 'https://fir-esp32-demo-6968d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp32-demo-6968d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxeWqKA5L2nVtwTJNWZe7vcVWBasmEaA',
    appId: '1:239664079474:android:ffa34ca6496c413611d8eb',
    messagingSenderId: '239664079474',
    projectId: 'fir-esp32-demo-6968d',
    databaseURL: 'https://fir-esp32-demo-6968d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp32-demo-6968d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY16ZO9I72poVr3WnhUe91Xlcyrh1tx44',
    appId: '1:239664079474:ios:357883b44ec0967711d8eb',
    messagingSenderId: '239664079474',
    projectId: 'fir-esp32-demo-6968d',
    databaseURL: 'https://fir-esp32-demo-6968d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp32-demo-6968d.appspot.com',
    iosBundleId: 'com.example.internetOfTheThings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY16ZO9I72poVr3WnhUe91Xlcyrh1tx44',
    appId: '1:239664079474:ios:de24c710f5de658511d8eb',
    messagingSenderId: '239664079474',
    projectId: 'fir-esp32-demo-6968d',
    databaseURL: 'https://fir-esp32-demo-6968d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp32-demo-6968d.appspot.com',
    iosBundleId: 'com.example.internetOfTheThings.RunnerTests',
  );
}